"use client";

import Link from "next/link";
import { usePathname } from "next/navigation";
import Navbar from "@/components/Navbar";

function PublicFooter() {
  return (
    <footer className="border-t border-[#c1123f]/10 bg-white/55 px-4 py-7 text-[#111111] sm:px-6">
      <div className="mx-auto flex max-w-7xl flex-col gap-4 text-sm leading-6 text-black/55 sm:flex-row sm:items-center sm:justify-between">
        <p className="max-w-3xl">
          All Companions, Conversations, And Images Are Generated By Artificial
          Intelligence And Do Not Represent Real People.
        </p>

        <nav className="flex shrink-0 gap-5" aria-label="Legal">
          <Link className="transition hover:text-black" href="/terms">
            Terms
          </Link>
          <Link className="transition hover:text-black" href="/privacy">
            Privacy Policy
          </Link>
          <Link className="transition hover:text-black" href="/refunds-cancellation">
            Refunds And Cancellation
          </Link>
        </nav>
      </div>
    </footer>
  );
}

export default function SiteChrome({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();
  const isAppRoute = pathname === "/app" || pathname.startsWith("/app/");
  const isWebChatRoute = pathname === "/chat" || pathname.startsWith("/chat/");
  const showPublicFooter = !isAppRoute && !isWebChatRoute;

  return (
    <>
      {isAppRoute ? null : <Navbar />}
      {children}
      {showPublicFooter ? <PublicFooter /> : null}
    </>
  );
}
