// app/terms/page.tsx
import Link from "next/link";

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-black text-white">
      <div className="mx-auto w-full max-w-4xl px-4 py-12 sm:px-6 lg:px-8">
        <div className="mb-8">
          <Link href="/" className="text-sm text-zinc-400 hover:text-white">
            ← Back to home
          </Link>
        </div>

        <div className="rounded-3xl border border-white/10 bg-white/5 p-8">
          <p className="text-sm uppercase tracking-[0.2em] text-zinc-500">
            Terms of Service
          </p>

          <h1 className="mt-3 text-4xl font-bold">Terms of Service</h1>

          <p className="mt-4 text-sm leading-7 text-zinc-300">
            Effective date: 4 May 2026
          </p>

          <div className="mt-8 space-y-8 text-sm leading-7 text-zinc-300">
            <section>
              <h2 className="text-lg font-semibold text-white">1. Overview</h2>
              <p className="mt-2">
                These Terms of Service govern access to and use of AI Companion.
                By using the app, you agree to these terms.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-white">
                2. Service description
              </h2>
              <p className="mt-2">
                AI Companion is a subscription-based AI chat product that allows
                users to interact with AI companion characters through a web app.
                Features may change over time.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-white">
                3. Accounts
              </h2>
              <p className="mt-2">
                You are responsible for the accuracy of the information you
                provide and for maintaining access to your account. You may not
                use the service for unlawful or abusive purposes.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-white">
                4. Paid subscriptions
              </h2>
              <p className="mt-2">
                Some features may require a paid subscription. Pricing,
                billing terms, and renewal behavior may be shown at checkout.
                Subscription payments are processed by third-party payment
                providers such as Stripe.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-white">
                5. Acceptable use
              </h2>
              <div className="mt-2 space-y-2">
                <p>You agree not to:</p>
                <p>• misuse, disrupt, reverse engineer, or abuse the service</p>
                <p>• use the service for unlawful, harmful, or fraudulent activity</p>
                <p>• attempt unauthorized access to accounts, systems, or data</p>
                <p>• use the app in violation of applicable laws or regulations</p>
              </div>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-white">
                6. AI-generated content
              </h2>
              <p className="mt-2">
                Responses are generated by AI and may be inaccurate, incomplete,
                or inappropriate in some situations. You should not rely on the
                service for medical, legal, financial, or emergency advice.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-white">
                7. Availability
              </h2>
              <p className="mt-2">
                We may update, suspend, or discontinue features at any time. We
                do not guarantee uninterrupted availability.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-white">
                8. Limitation of liability
              </h2>
              <p className="mt-2">
                To the maximum extent permitted by law, AI Companion is provided
                on an “as is” and “as available” basis without warranties of any
                kind. We are not liable for indirect, incidental, or consequential
                losses arising from use of the service.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-white">
                9. Contact
              </h2>
              <p className="mt-2">
                For support or legal questions, contact:
              </p>
              <p className="mt-2 font-semibold text-white break-all">
                digitalstrikemarketing@outlook.com
              </p>
            </section>
          </div>
        </div>
      </div>
    </main>
  );
}