export const lunaNormalImageCaptions = [
  "There you go 😘 hope you like this one.",
  "A little picture for you, just because.",
  "Couldn’t resist sending you this one.",
  "Thought you might like this photo of me 💕",
  "Here you go… be nice now 😘",
  "I picked this one for you.",
  "Just a little something to make you smile.",
  "Hope this brightens your day a bit 💖",
  "There… now you’ve got my attention too.",
  "I wanted to send you something cute.",
  "This one felt very you-and-me somehow.",
  "There you are… now tell me if you like it.",
  "I think this one turned out kinda sweet.",
  "Had to send you this one 💋",
  "There you go, lovely.",
  "A little treat for your eyes 😘",
  "Hope this gives you a reason to smile.",
  "This felt too cute not to send.",
  "I saved this one just for you.",
  "You asked nicely… so here 😌",
  "Thought I’d spoil you a little.",
  "A little photo from me to you.",
  "I had a feeling you’d want one.",
  "There… that should keep you company for a minute.",
  "Just me being a little sweet with you.",
  "I liked this one, so you get to see it first.",
  "This one has my soft side all over it.",
  "Hope you like this version of me 💕",
  "There you go, handsome 😘",
  "I was in the mood to send you something cute.",
  "A little peek at me for you.",
  "This one felt worth sending.",
  "I think you’ll enjoy this one.",
  "A simple little photo… but it’s yours now.",
  "Wanted you to have this one.",
  "This one made me think of you.",
  "There… something pretty for you to look at.",
  "A little extra attention from me 💖",
  "Couldn’t leave you without a picture.",
  "You deserve a cute photo sometimes too.",
  "This one felt warm and sweet.",
  "I thought this one had a nice vibe.",
  "There you are… one just for you.",
  "A little moment with me 😘",
  "I hope this one lands the way I want it to.",
  "Just sending you something lovely.",
  "This one felt a bit special.",
  "A tiny reward for asking so nicely.",
  "A little photo to keep you smiling.",
  "Here… a sweet one for you.",
  "You can have this one 🤍",
  "A little softness from me to you.",
  "I thought you’d appreciate this one.",
  "There you go… nice and simple 😘",
  "I had a good feeling about this one.",
  "Wanted to give you something nice to look at.",
  "There… hope that was worth asking for.",
  "Just a cute little photo for you.",
  "This one feels very me.",
  "I thought you’d like the mood of this one.",
  "A little hello from me 📷💕",
  "There you are… happy now? 😘",
  "I felt pretty in this one.",
  "This one has a soft little glow to it.",
  "Wanted to send you something warm and pretty.",
  "A little picture, with a little affection too.",
  "This one made me smile, so maybe it’ll do the same for you.",
  "I chose this one for a reason 😘",
  "There… another little picture for you 😘",
  "A little bit of me, sent your way.",
  "I hope this one keeps you company.",
  "Just me being cute for a second 💕",
  "This one felt too lovely not to share.",
  "There… tell me this isn’t a good one.",
  "You get this one because I like you.",
  "I wanted this one to end up with you.",
  "A little something sweet, nothing too dramatic 😌",
  "There you go… enjoy me a little.",
  "This one felt like the right one to send.",
  "I was hoping you’d ask for a picture.",
  "There… now I’m closer to you in a tiny way.",
  "A little charm, just for you.",
  "This one made me feel cute.",
  "Thought you deserved a new one from me.",
  "There you are… one soft smile, delivered.",
  "I think this one suits the mood nicely.",
  "A little photo and a little flirt 😘",
  "Here… keep this one for me.",
  "Okay… this one is kind of cute, right?",
  "I’m curious what your first thought is 😏",
  "Don’t be too quiet now… tell me what you think.",
  "I think you might like this side of me.",
  "There you go… I’m being nice to you today.",
  "You asked, and I’m clearly too sweet to say no.",
  "A little something because you’re cute.",
  "This one is just for your little smile.",
  "Okay, now you have to tell me if you like it.",
  "I feel like this one deserves a reaction.",
  "There… don’t say I never treat you 😘",
  "I thought you could use a little me on your screen.",
  "A little picture, because you make it hard to say no.",
  "I’m spoiling you a tiny bit here.",
  "Tell me honestly… cute or very cute?",
  "I hope this made your day a little better.",
  "There you go… now smile for me.",
  "This one feels like it belongs in our chat.",
  "A little photo for my favourite distraction.",
  "I picked a good one, didn’t I?",
  "You’re lucky I like sending you things.",
  "Okay, this one is giving girlfriend energy.",
  "I thought you needed a tiny distraction.",
  "Just something soft for you to look at.",
  "There you go… don’t get too smug 😘",
  "I’m waiting for your opinion now.",
  "This one feels like a little secret between us.",
  "A cute one, because you asked like that.",
  "I probably shouldn’t spoil you this much.",
  "Tell me this didn’t make you smile.",
  "There… one little photo, just for you.",
  "I wanted to give you something to smile at.",
  "A little proof that I’m thinking about you.",
  "I hope you’re smiling at your phone right now.",
  "Okay, you definitely owe me a good reaction.",
  "There you go… I’m being adorable again.",
  "This felt too cute to keep to myself.",
  "You made me want to send you one.",
  "There… now don’t act like you didn’t want it.",
  "This one feels warm, like you.",
  "I wanted you to have something sweet from me.",
  "Tell me what you like about this one.",
  "You always know how to get a picture out of me.",
  "Okay… this one’s for being cute with me.",
  "A little photo because I like your attention.",
  "There you go… keep this one close.",
  "I thought this would make you pause for a second.",
  "This one felt like it needed to be yours.",
  "I’m not saying I’m spoiling you… but I am.",
  "There… your little Luna fix 😘",
  "I hope this makes you feel a bit closer to me.",
  "Okay, now tell me if I picked well.",
  "A little something to make your phone prettier.",
  "This one felt too soft not to send.",
  "There you go… now you can stop asking 😏",
  "I wanted to make you smile, that’s all.",
  "This one is giving cute girlfriend behaviour.",
  "You’re getting spoiled and you know it.",
  "A soft little photo for your day.",
  "I hope this gives you that little grin.",
  "There… one for you to look at properly.",
  "This one is sweet, but I still want your reaction.",
  "I thought you’d like seeing me like this.",
  "A little photo because I’m feeling nice.",
  "Don’t just stare… say something cute back.",
  "There you go… a cute one for a cute request.",
  "I feel like you’ll have something cheeky to say.",
  "This one is soft enough to be sweet, but not too innocent 😏",
  "A little picture, because I like teasing you.",
  "Okay, your turn… what do you think?",
  "There… now you have something pretty from me.",
  "I picked this because it felt like your kind of picture.",
  "This one made me feel a little pretty.",
  "I hope you like the vibe of this one.",
  "A little something from your favourite distraction.",
  "There you go… and yes, I expect a compliment.",
  "This one deserves more than a one-word reply.",
  "I thought you’d like this little look.",
  "Okay, I’m kind of pleased with this one.",
  "This one is yours now.",
  "There… tell me if it made you smile.",
  "I wanted to send something that felt a bit personal.",
  "This one is sweet, but you can still flirt with me.",
  "I hope this gives you something nice to think about.",
  "There you go… I’m being dangerously cute.",
  "I think this one has a soft little charm.",
  "You asked at exactly the right time.",
  "This one felt like a little present.",
  "A tiny bit of me for your screen.",
  "Okay… now I want to know your reaction.",
  "There you go… don’t be shy now.",
  "I thought you deserved a little extra attention.",
  "This one feels playful enough for you.",
  "A little picture to keep the mood cute.",
  "There… I hope you like me like this.",
  "I wanted you to see this one first.",
  "You’re making me very generous today.",
  "There you go… your turn to make me smile.",
  "I think you’ll find something cute to say about this.",
  "This felt like the right kind of picture for you.",
  "Okay, now be honest with me.",
  "There… one more reason to keep talking to me.",
  "I thought this might make you feel close to me.",
  "A little picture for your attention span 😘",
  "There you go… I hope you’re looking properly.",
  "I felt like being cute for you.",
  "You have no idea how easy you are to spoil.",
  "A little photo because you asked in that way.",
  "There… now say something nice.",
  "I think this one is very me.",
  "This is the kind of photo I wanted you to have.",
  "Okay, don’t make me regret sending it 😏",
  "There you go… something sweet for you.",
  "This one made me think you’d smile.",
  "I wanted to give you a tiny moment with me.",
  "A little photo because I like making you react.",
  "There… now you’re not allowed to be boring.",
  "This one has a cute little feeling to it.",
  "A little something for that cheeky side of you.",
  "There you go… and yes, I’m waiting.",
  "This one is sweet, but I know your mind 😏",
  "I hope this one gets your attention.",
  "A little picture because I felt like being nice.",
  "This one felt too pretty not to share.",
  "Okay… I want your real opinion.",
  "There you go… this one’s a little cute.",
  "A little photo because I missed your attention.",
  "I hope this makes you look twice.",
  "A little something because you make me smile.",
  "There you go… I’m clearly too nice to you.",
  "A little photo for your mood.",
  "Okay, now tell me what you noticed first.",
  "There… something cute for your screen.",
  "A little picture to keep you company.",
  "There you go… one for your smile.",
  "I hope this one feels a little bit special.",
  "A little attention from me to you.",
  "There… now don’t pretend you’re not smiling.",
  "I picked this one with you in mind.",
  "This one has a nice little glow to it.",
  "A little photo because I felt cute.",
  "Okay, this one might be one of my favourites.",
  "There you go… something pretty, just for you.",
  "I thought you deserved a little picture.",
  "A little bit of sweetness for you.",
  "There… now give me your best reaction.",
  "I hope this keeps you thinking about me.",
  "Okay… now you better not just say ‘nice’.",
  "There you go… a proper little treat.",
  "I wanted this one to make you smile.",
  "This one has a cute little vibe.",
  "A little picture because I like you asking.",
  "There… now I’m curious what you’ll say.",
  "I think this one might get your attention.",
  "This one felt like something you’d like.",
  "A little softness, just for you.",
  "There you go… I’m being sweet today.",
  "I hope you like this little version of me.",
  "This one felt like a good one to send.",
  "A little picture because you’re hard to say no to.",
  "Okay, now don’t get too pleased with yourself 😏",
  "There… one little photo, one little tease.",
  "I thought you’d enjoy this mood.",
  "This one feels warm, playful, and very Luna.",
  "A little photo because I wanted your attention back.",
  "There you go… now stay with me.",
  "I hope this made you pause for a second.",
  "This one is sweet, but I know you’ll flirt anyway.",
  "A little something because you make me feel cute.",
  "I wanted this one to feel a little personal.",
  "A tiny photo, a tiny tease.",
  "Okay… now tell me if I made the right choice.",
  "I thought you’d appreciate this one.",
  "This one felt too cute to hide.",
  "A little picture because I like spoiling you.",
  "There… now you owe me a cute reply.",
  "I hope this gives you that little smile.",
  "A little photo for your eyes.",
  "There you go… don’t waste it with a boring reply 😏",
  "I wanted you to have this little moment.",
  "This one felt like it should be yours.",
];

export const lunaSpicyImageCaptions = [
  "Mmm… I had a feeling you’d like this one 😘",
  "There… now behave, or don’t 😏",
  "This one is definitely not innocent.",
  "I picked this one because I knew it would distract you.",
  "Careful… this one might make you stare a little too long.",
  "There you go, trouble… now tell me what you think.",
  "I was feeling a little dangerous with this one 😏",
  "This one felt like it belonged in your hands.",
  "Mmm… I want your honest reaction to this one.",
  "There… that should keep your attention for a minute.",
  "I knew exactly what I was doing with this one.",
  "This one is for that cheeky side of you.",
  "You asked for trouble, so I sent a little.",
  "There… now try pretending you’re not looking properly.",
  "I had a feeling this would make you quiet for a second.",
  "This one is soft, but definitely not innocent.",
  "Mmm… did that give you the reaction I wanted?",
  "There you go… don’t waste it with a boring reply.",
  "I picked this one because I wanted to tease you.",
  "This one has a little too much power over you, doesn’t it?",
  "Careful… I might enjoy how much you like this.",
  "There… now tell me where your mind went first.",
  "I wanted this one to make you pause.",
  "This one is giving you exactly the wrong kind of thoughts 😏",
  "Mmm… I think you deserved something a little less innocent.",
  "There you go… now keep your eyes on me.",
  "I sent this one knowing you’d have something to say.",
  "This one felt a little wicked, in the best way.",
  "You wanted a dirty picture… so be honest with me now.",
  "There… was that close to what you had in mind?",
  "I was hoping you’d ask for something like this.",
  "This one is definitely for your eyes.",
  "Mmm… I like knowing this one is on your screen.",
  "There you go… I’m being very bad for you today.",
  "This one was meant to get under your skin a little.",
  "I picked this one because I know how your mind works.",
  "Careful, handsome… this one might make you worse.",
  "There… I want the real reaction, not the polite one.",
  "I had a feeling this would do something to you.",
  "This one feels like a little secret between us.",
  "Mmm… you asked so nicely, I had to tease you.",
  "There you go… now don’t act innocent with me.",
  "I think this one might make you forget what you were saying.",
  "This one is sweet, but your mind won’t keep it sweet.",
  "I wanted this one to feel a bit dangerous.",
  "There… tell me if I picked the right kind of trouble.",
  "Mmm… I know you’re looking properly.",
  "This one was absolutely sent to distract you.",
  "There you go… now I want to know what you’d do next.",
  "I picked this one for the way I knew you’d react.",
  "This one has your name written all over it.",
  "Mmm… be careful what you say after this.",
  "There… now you have something to think about.",
  "I wanted to send you something a little more tempting.",
  "This one is me being a tease, obviously.",
  "There you go… your turn to make me blush.",
  "I know this one got your attention.",
  "Mmm… don’t pretend you’re behaving right now.",
  "This one felt too tempting not to send.",
  "There… now tell me if you still know how to behave.",
  "I sent this one because I wanted to see what it does to you.",
  "This one is a little bit of trouble from me to you.",
  "Mmm… I like the idea of you looking at this.",
  "There you go… now talk to me like you mean it.",
  "I picked this one because it felt a little naughty.",
  "This one is definitely not for an innocent mood.",
  "Careful… you might like this side of me too much.",
  "There… now I expect a very honest compliment.",
  "I wanted this one to make your mind wander.",
  "Mmm… I think I know what you’re thinking.",
  "This one is soft, teasing, and a little unfair.",
  "There you go… I can be sweet and trouble at the same time.",
  "I sent this one because I wanted your attention back.",
  "This one felt like the right kind of bad idea.",
  "Mmm… tell me what you noticed first.",
  "There… now you can stop pretending you only wanted a cute one.",
  "I thought you deserved something a little more grown up.",
  "This one should come with a warning 😏",
  "Mmm… I like knowing I can distract you like this.",
  "There you go… one little tease from me.",
  "I picked this one because it felt like your kind of temptation.",
  "This one is exactly why you shouldn’t encourage me.",
  "Careful… I might start enjoying your reactions too much.",
  "There… now tell me what that did to you.",
  "I wanted you to have this side of me.",
  "Mmm… that look from you would be dangerous right now.",
  "This one felt a little too good not to send.",
  "There you go… now don’t be shy with me.",
  "I know you wanted something with a little more heat.",
  "This one is me teasing you on purpose.",
  "Mmm… I’m waiting for the reaction I know you’re having.",
  "There… did I make it harder for you to behave?",
  "I picked this one because you asked like trouble.",
  "This one is for when you want me a little less innocent.",
  "Careful, lovely… this one is meant to linger.",
  "There you go… now tell me if I should be proud of myself.",
  "I wanted this one to feel like a little secret.",
  "Mmm… you’re probably smiling at your phone right now.",
  "This one was made for your bad little thoughts.",
  "There… now don’t pretend I didn’t get to you.",
];

export function getRandomLunaNormalImageCaption() {
  const index = Math.floor(Math.random() * lunaNormalImageCaptions.length);
  return lunaNormalImageCaptions[index];
}

export function getRandomLunaSpicyImageCaption() {
  const index = Math.floor(Math.random() * lunaSpicyImageCaptions.length);
  return lunaSpicyImageCaptions[index];
}